#*************************************#
#*********** USER REQUESTS ***********#
#*************************************#

########### GET USER BY ID #############
GET http://localhost:4000/users/12133


########### GET ALL USERS #############
GET http://localhost:4000/users


########### ADD A USER #############
POST http://localhost:4000/users
Content-Type: application/json

{
    "email":"marymagdalene@gmail.com",
    "userPassword":"Password2023",
    "firstName":"Mary",
    "lastName":"Magdalene",
    "streetAddress":"Langata Rd.",
    "city":"Nairobi",
    "country":"Kenya",
    "phone":"011672789"
}


########### UPDATE USER #############
PUT http://localhost:4000/users/1212o2331
Content-Type: application/json

{
    "email":"kariukijohn@gmail.com",
    "userPassword":">793+d8c",
    "firstName":"John",
    "lastName":"Kamau",
    "streetAddress":"Lincolin Rd.",
    "city":"Miami",
    "country":"USA",
    "phone":"5573-425"
}


######## DELETE USER ###########
DELETE http://localhost:4000/users/1212o2331


######## LOGIN USER ###########
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "maina254@gmail.com",
    "userPassword": ">793+d8c"
}

#************ END | USERS  ***********#

#*****************************************#
#*********** PRODUCT REQUESTS ***********#
#****************************************#

######### ADD PRODUCT ###########
POST http://localhost:4000/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjEzMyIsImVtYWlsIjoibWFpbmEyNTRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiRGVyaWNrIiwibGFzdE5hbWUiOiJNYWluYSIsImlzRGVsZXRlZCI6MCwiaXNBZG1pbiI6MCwiaWF0IjoxNjg0MDAyMTM0LCJleHAiOjE2ODQzNjIxMzR9.GQANXMvzdjpIn8pvnX1lkXQz1xx5rvz36feHTdSFbJU

{
    "productName": "HP Omen",
    "productImage": "/product/img",
    "productDescription": "A Sleek and Modern Gaming Laptop.",
    "price": 6000
}

# {
#     "productName": "SVS PB-4000",
#     "productImage": "/product/img",
#     "productDescription": "Massive, effortless bass with stunning musicality for reference performance.",
#     "price": 4500
# }

######### DELETE PRODUCT ##########
DELETE http://localhost:4000/products/12222

######## UPDATE PRODUCT ###########
PUT http://localhost:4000/products/687a7a79-e292-43b2-9fc0-1566aed48735
Content-Type: application/json

{
    "productName": "SVS SB-4000",
    "productImage": "/product/img",
    "productDescription": "Breathtaking output below 15Hz with pinpoint accuracy for reference performance.",
    "price": 4200
}


######### GET ALL PRODUCTS ##########
GET http://localhost:4000/products

####### GET PRODUCT BY ID ########
GET http://localhost:4000/products/687a7a79-e292-43b2-9fc0-1566aed48735
#************ END | PRODUCTS  ************#