#*************************************#
#*********** USER REQUESTS ***********#
#*************************************#

########### GET USER BY ID #############
GET http://localhost:4000/users/bee2f213-39d2-42a3-990c-f9836fbb848e


########### GET ALL USERS #############
GET http://localhost:4000/users


########### ADD A USER #############
POST http://localhost:4000/users
Content-Type: application/json

# {
#     "email":"marymagdalene@gmail.com",
#     "userPassword":"Password2023",
#     "firstName":"Mary",
#     "lastName":"Magdalene",
#     "streetAddress":"Langata Rd.",
#     "city":"Nairobi",
#     "country":"Kenya",
#     "phone":"011672789"
# }

{
    "email":"petercullen@gmail.com",
    "userPassword":"Tr4ns4mars",
    "firstName":"Peter",
    "lastName":"Cullen",
    "streetAddress":"Lincolin Rd.",
    "city":"New York",
    "country":"USA",
    "phone":"555-1167"
}


########### UPDATE USER #############
PUT http://localhost:4000/users/0aafae19-8d15-455b-a1a6-2aeb77534c88
Content-Type: application/json

{
    "email":"stacknewbie@gmail.com",
    "userPassword":"teddy428!",
    "firstName":"Teddy",
    "lastName":"Omondi",
    "streetAddress":"Kisumu - Kakamega Rd.",
    "city":"Kakamega",
    "country":"Kenya",
    "phone":"0788783652"
}


######## DELETE USER ###########
DELETE http://localhost:4000/users/1212o2331


######## LOGIN USER ###########
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "petercullen@gmail.com",
    "userPassword": "Tr4ns4mars"
}

#************* END | USERS  ************#
#                                       #
#             WHITE SPACE               #
#                                       #
#***************************************#
#********** PRODUCT REQUESTS ***********#
#***************************************#

######### ADD PRODUCT ###########
POST http://localhost:4000/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzFjMDcyYS1hODlhLTRjZmItODBhZi1jNjZjOGY1ODk2N2QiLCJlbWFpbCI6InBldGVyY3VsbGVuQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IlBldGVyIiwibGFzdE5hbWUiOiJDdWxsZW4iLCJpc0RlbGV0ZWQiOjAsImlzQWRtaW4iOjAsImVtYWlsc1JlY2VpdmVkIjowLCJpYXQiOjE2ODQxNDQ4NDAsImV4cCI6MTY4NDUwNDg0MH0.ysz2w7IVkyC9HV2MgbmMXD9Rx43VTOyKC4cFa9cL0Sc

{
    "productName": "Samsung Galaxy",
    "productImage": "/product/img",
    "productDescription": "Samsung Galaxy A24.",
    "price": 7000
}

# {
#     "productName": "SVS PB-4000",
#     "productImage": "/product/img",
#     "productDescription": "Massive, effortless bass with stunning musicality for reference performance.",
#     "price": 4500
# }

######### DELETE PRODUCT ##########
DELETE http://localhost:4000/products/12222

######## UPDATE PRODUCT ###########
PUT http://localhost:4000/products/687a7a79-e292-43b2-9fc0-1566aed48735
Content-Type: application/json

{
    "productName": "SVS SB-4000",
    "productImage": "/product/img",
    "productDescription": "Breathtaking output below 15Hz with pinpoint accuracy for reference performance.",
    "price": 4300
}


######### GET ALL PRODUCTS ##########
GET http://localhost:4000/products

####### GET PRODUCT BY ID ########
GET http://localhost:4000/products/6c1b6fd0-3bf0-44ce-b05c-edc20151bc35
#************ END | PRODUCTS  ************#