#********** TESTS *********#

PUT http://localhost:8000/reset/password/stacknewbie@gmail.com
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYWFmYWUxOS04ZDE1LTQ1NWItYTFhNi0yYWViNzc1MzRjODgiLCJlbWFpbCI6InN0YWNrbmV3YmllQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ik51ciIsImxhc3ROYW1lIjoiT21vbmRpIiwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJlbWFpbHNSZWNlaXZlZCI6MCwiaWF0IjoxNjg0Nzg1NjQ1LCJleHAiOjE2ODUxNDU2NDV9.sPItvxu6-zafyAVeoeZz7XNmapyeaPCSn60iTwJ4nHk

{
    "email": "stacknewbie@gmail.com",
    "userPassword": "newpwd2023"
}


##### REQUEST FOR PASSWORD RESET | When a user is redirected to this page, 
#       a new token is assigned to them       
#
#                **Password Reset Page**
#
#               Email: __________________
#       
#                 ********************
#                 |   RESET BUTTON   |
#                 ********************
# 
# THE FOLLOWING REQUEST WITH SEND AN EMAIL WITH A RESET LINK
GET http://localhost:8000/reset/stacknewbie@gmail.com
